In [34]:
import math
import numpy as np
a = np.random.random((10,3))
print(a)
n=a[np.arange(10),np.abs(a - 0.5).argmin(axis=1)]
print(n)

[[0.09844024 0.88618903 0.03452631]
 [0.17290445 0.09655627 0.90515276]
 [0.27549743 0.65703494 0.41400648]
 [0.90343043 0.61368495 0.68666797]
 [0.38311459 0.84590956 0.29427521]
 [0.38593332 0.73484685 0.74809553]
 [0.151646   0.80367753 0.46462202]
 [0.93736193 0.06857238 0.94066429]
 [0.71543116 0.94711587 0.78627819]
 [0.60262993 0.5569865  0.6640288 ]]
[0.88618903 0.17290445 0.41400648 0.61368495 0.38311459 0.38593332
 0.46462202 0.06857238 0.71543116 0.5569865 ]


In [18]:
import numpy as np
a = np.random.random((6,6))
print(a)
print(a.sum(axis=1)/a.min(axis=0))

[[0.61371196 0.58356848 0.09625288 0.89351316 0.33689871 0.05610506]
 [0.50543583 0.81377862 0.13878215 0.8081601  0.43008446 0.88860076]
 [0.52976546 0.17605686 0.2237265  0.06684021 0.71629053 0.2408858 ]
 [0.28338525 0.04777804 0.29453179 0.19610486 0.99098087 0.0792897 ]
 [0.98606316 0.5660475  0.37891895 0.93491312 0.89108494 0.84022527]
 [0.02012931 0.89123549 0.82518515 0.68133958 0.52358377 0.34300613]]
[128.17381647  75.03116819  20.29617528  28.30737147  13.64580162
  58.54158774]


In [32]:
import numpy as np
x = np.array([6,2,0,3,0,0,5,7,0])
print(x)
print(x[np.where(x[:-1]==0)[0]+1].max())

[6 2 0 3 0 0 5 7 0]
5


In [33]:
import numpy as np
x = np.ones(10)
i=np.array([0,1,2,3,5,5,5,8])
print(x,i)
np.add.at(x,i,1)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [0 1 2 3 5 5 5 8]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [35]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a)
n=a.shape[0]
k=0
for i in range(n*2-1):
    for j in range(i+1):
        if j<n and i-j<n:
            print(i,":",[a[j,i-j]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0 : [0]
1 : [1]
1 : [4]
2 : [2]
2 : [5]
2 : [8]
3 : [3]
3 : [6]
3 : [9]
3 : [12]
4 : [7]
4 : [10]
4 : [13]
5 : [11]
5 : [14]
6 : [15]


In [3]:
import math
import numpy as np
def get_score(pts, centroids, labels):
    return sum( \
        np.linalg.norm(pts[labels == label] - centroids[label], axis=1).sum() \
            for label in range(centroids.shape[0]) \
    ) / pts.shape[0]
def kmeans(obs, k_or_guess, iter=10, thresh=1e-04):
    centroids = np.random.random((k_or_guess, obs.shape[1]))
    labels = get_labels(obs, centroids)
    score = get_score(obs, centroids, labels)
    best_score = score
    best_centroids = centroids
    while True:
        centroids = np.array([obs[labels == label].mean(axis=0) for label in range(centroids.shape[0])])
        labels = get_labels(obs, centroids)
        old_score = score
        score = get_score(obs, centroids, labels)

        if score < best_score:
            best_score = score
            best_centroids = centroids
        
        if not isinstance(k_or_guess, np.ndarray):
            iter = iter - 1
            if iter == 0:
                break
        
        if abs(score - old_score) < thresh:
            break

    return best_centroids, best_score
