In [28]:
import math
import numpy as np
a = np.random.random((10,3))
print(a)
for i in range(10):
    k=0.5
    n=0
    for j in range(3):
        if abs(a[i][j]-0.5)<k:
            k=abs(a[i][j]-0.5)
            n=a[i][j]
    print(n)

[[0.76077623 0.13116069 0.84120795]
 [0.97657674 0.15527495 0.16040592]
 [0.34054152 0.64177348 0.81898039]
 [0.40112758 0.45875265 0.96148934]
 [0.35870849 0.4747925  0.29362166]
 [0.59198989 0.28212206 0.74860692]
 [0.71709895 0.93937563 0.19290164]
 [0.94490748 0.62801361 0.46299723]
 [0.56166832 0.2053925  0.07679477]
 [0.72625256 0.53400794 0.74822879]]
0.7607762263877376
0.16040592160912803
0.641773475186287
0.4587526523660599
0.47479249564196446
0.5919898949751241
0.7170989463514212
0.46299722582723635
0.5616683237079096
0.5340079442031412


In [41]:
import numpy as np
a = np.random.random((6,6))
print(a)
for i in range(6):
    b=np.sum(a[i])
    m=1
    for j in range(6):
        if a[j][i]<m:
            m=a[j][i]
    print(b/m)

[[0.27088108 0.00982235 0.27503129 0.63121353 0.15609868 0.17036547]
 [0.10589455 0.57732299 0.46544934 0.18338235 0.31067304 0.87942989]
 [0.80053925 0.65319803 0.12190865 0.84722501 0.01024682 0.41051901]
 [0.32327638 0.78843089 0.89102267 0.35068509 0.6523321  0.42728306]
 [0.32705419 0.32638968 0.5053536  0.45692801 0.66432194 0.95477657]
 [0.83178024 0.52913053 0.00321774 0.23448359 0.48520748 0.99339204]]
14.29169274267013
256.7767411802427
883.7381446898263
18.720614565164368
315.69055049381575
18.06241398612527


In [48]:
import numpy as np
x = np.array([6,2,0,3,0,0,5,7,0])
print(x)
m=0
for i in range(9):
    if x[i]>m and x[i+1]==0:
        m=x[i]
print(m)

[6 2 0 3 0 0 5 7 0]
7


In [51]:
import numpy as np
x = np.ones(10)
i=np.array([0,1,2,3,5,5,5,8])
print(x,i)
for j in range(10):
    for k in i:
        if j==k:
            x[j]=x[j]+1
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [0 1 2 3 5 5 5 8]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [19]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a)
n=a.shape[0]
k=0
for i in range(n*2-1):
    for j in range(i+1):
        if j<n and i-j<n:
            print(i,":",[a[j,i-j]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0 : [0]
1 : [1]
1 : [4]
2 : [2]
2 : [5]
2 : [8]
3 : [3]
3 : [6]
3 : [9]
3 : [12]
4 : [7]
4 : [10]
4 : [13]
5 : [11]
5 : [14]
6 : [15]


In [3]:
import math
import numpy as np
def get_score(pts, centroids, labels):
    return sum( \
        np.linalg.norm(pts[labels == label] - centroids[label], axis=1).sum() \
            for label in range(centroids.shape[0]) \
    ) / pts.shape[0]
def kmeans(obs, k_or_guess, iter=10, thresh=1e-04):
    centroids = np.random.random((k_or_guess, obs.shape[1]))
    labels = get_labels(obs, centroids)
    score = get_score(obs, centroids, labels)
    best_score = score
    best_centroids = centroids
    while True:
        centroids = np.array([obs[labels == label].mean(axis=0) for label in range(centroids.shape[0])])
        labels = get_labels(obs, centroids)
        old_score = score
        score = get_score(obs, centroids, labels)

        if score < best_score:
            best_score = score
            best_centroids = centroids
        
        if not isinstance(k_or_guess, np.ndarray):
            iter = iter - 1
            if iter == 0:
                break
        
        if abs(score - old_score) < thresh:
            break

    return best_centroids, best_score
